# OpenAPI Version.
openapi: "3.0.1"

# Metadata about the API
info:
  title: Bates Motel API
  description: This API represents the operation of the Bates Motel
  termsofService: terms.batesmotel.com
  contact:
    name: Norma Bates
    url: team.batesmotel.com
    email: normabates@batesmotel.com
  license:
    name: MPL 2.0
    url: https://www.mozilla.org/en-US/MPL/2.0/
  version: "0.1.0"

# Servers
servers:
  - url: http://api.batesmotel.com/v1
    description: Production Server

paths:
  /hosts:
    get:
      parameters:
        - name: hosts
          in: query
          required: false
          
      responses:
        200:
          description: ok