# Open API
swagger: "2.0"

# info:
info:
  version: 0.1.0
  title: Meme Meister
  description: API to create memes
  termsOfService: Check our Terms of Service
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT

consumes:
  - application/json
produces:
  - application/json

host: api.mememeister.com
basePath: /v1
schemes:
  - http

paths:
  /meme:
    # Create a meme
    post:
      description: Create a new meme
      parameters:
        - name: topcaption
          description: String need to be URL-encoded
          in: query
          required: true
          type: string
        - name: bottomcaption
          description: String need to be URL-encoded
          in: query
          required: true
          type: string
        - name: image
          in: formData
          required: true
          type: file
            - image/jpeg
            - image/gif
            - image/png
      security:
        - oauthFacebook:
          - read:memes
          - write:memes
      responses:
        200:
          description: Successful
          schema: file
            - image/jpeg
    
    # Get list of memes and captions
    get:
      description: Get a list of all memes
      parameters:
        - name: title
          in: search
          required: false
          type: string
      security:
        - oauthFacebook:
          - read:memes
      responses:
        200:
          description: Successful
          schema: 
            type: array
            items:
              '#/definitions/memedefinition'
  
  /meme/{meme-id}:
    # Get a specific meme
    get:
      description: Get a specific meme
      parameters:
      security:
        - oauthFacebook:
          - read:memes
      responses:
        200:
          description: Successful
    
    # Delete a specific meme
    delete:
      description: Delete a specific meme
      parameters:
      security:
        - oauthFacebook:
          - write:memes
      responses:
        200:
          description: Successful

  
securityDefinitions:
  oauthFacebook:
    description: Facebook OAuth
    type: oauth2
    authorizationUrl: https://dev.facebook.com/oauth/authenticate
    flow: implicit
    scopes:
      write:memes: Modify memes in your account
      read:memes: Read memes in your account